#!/bin/bash

# Upping the maxFalseAlarmRate makes it detect less
# more numStages means slower training but more detail in stages; needed to find a sweet spot for efficiency and detail
# numPos and numNeg determine how much you detect
#   if i'm detecting too much, just increase the numNeg 

# this one is pretty good
# rm old_cascades/cascade_019/*.xml && C:/Users/Jayare/Downloads/opencv/build/x64/vc15/bin/opencv_traincascade.exe -data old_cascades/cascade_019/ -vec pos.vec -bg neg.txt -w 24 -h 24 -precalcValBufSize 10000 -precalcIdxBufSize 10000 -numPos 110 -numNeg 180 -numStages 15 -maxFalseAlarmRate 0.15 -minHitRate 0.999999 > old_cascades/cascade_019/command.txt
# rm old_cascades/cascade_019/*.xml && C:/Users/Jayare/Downloads/opencv/build/x64/vc15/bin/opencv_traincascade.exe -data old_cascades/cascade_019/ -vec pos.vec -bg neg.txt -w 24 -h 24 -precalcValBufSize 10000 -precalcIdxBufSize 10000 -numPos 130 -numNeg 200 -numStages 15 -maxFalseAlarmRate 0.15 -minHitRate 0.999999 > old_cascades/cascade_019/command.txt
# rm old_cascades/cascade_019/*.xml && C:/Users/Jayare/Downloads/opencv/build/x64/vc15/bin/opencv_traincascade.exe -data old_cascades/cascade_019/ -vec pos.vec -bg neg.txt -w 24 -h 24 -precalcValBufSize 10000 -precalcIdxBufSize 10000 -numPos 130 -numNeg 220 -numStages 15 -maxFalseAlarmRate 0.15 -minHitRate 0.999999 > old_cascades/cascade_019/command.txt
# rm old_cascades/cascade_019/*.xml && C:/Users/Jayare/Downloads/opencv/build/x64/vc15/bin/opencv_traincascade.exe -data old_cascades/cascade_019/ -vec pos.vec -bg neg.txt -w 24 -h 24 -precalcValBufSize 10000 -precalcIdxBufSize 10000 -numPos 150 -numNeg 250 -numStages 15 -maxFalseAlarmRate 0.15 -minHitRate 0.999999 > old_cascades/cascade_019/command.txt
# rm old_cascades/cascade_019/*.xml && C:/Users/Jayare/Downloads/opencv/build/x64/vc15/bin/opencv_traincascade.exe -data old_cascades/cascade_019/ -vec pos.vec -bg neg.txt -w 24 -h 24 -precalcValBufSize 10000 -precalcIdxBufSize 10000 -numPos 150 -numNeg 280 -numStages 15 -maxFalseAlarmRate 0.15 -minHitRate 0.999999 > old_cascades/cascade_019/command.txt
# rm old_cascades/cascade_019/*.xml && C:/Users/Jayare/Downloads/opencv/build/x64/vc15/bin/opencv_traincascade.exe -data old_cascades/cascade_019/ -vec pos.vec -bg neg.txt -w 24 -h 24 -precalcValBufSize 10000 -precalcIdxBufSize 10000 -numPos 170 -numNeg 280 -numStages 15 -maxFalseAlarmRate 0.15 -minHitRate 0.999999 > old_cascades/cascade_019/command.txt
# rm old_cascades/cascade_019/*.xml && C:/Users/Jayare/Downloads/opencv/build/x64/vc15/bin/opencv_traincascade.exe -data old_cascades/cascade_019/ -vec pos.vec -bg neg.txt -w 24 -h 24 -precalcValBufSize 10000 -precalcIdxBufSize 10000 -numPos 170 -numNeg 300 -numStages 15 -maxFalseAlarmRate 0.15 -minHitRate 0.999999 > old_cascades/cascade_019/command.txt

# this is probably the best one yet 
# rm old_cascades/cascade_019/*.xml && C:/Users/Jayare/Downloads/opencv/build/x64/vc15/bin/opencv_traincascade.exe -data old_cascades/cascade_019/ -vec pos.vec -bg neg.txt -w 24 -h 24 -precalcValBufSize 10000 -precalcIdxBufSize 10000 -numPos 170 -numNeg 330 -numStages 15 -maxFalseAlarmRate 0.15 -minHitRate 0.999999 > old_cascades/cascade_019/command.txt
# rm old_cascades/cascade_019/*.xml && C:/Users/Jayare/Downloads/opencv/build/x64/vc15/bin/opencv_traincascade.exe -data old_cascades/cascade_019/ -vec pos.vec -bg neg.txt -w 24 -h 24 -precalcValBufSize 10000 -precalcIdxBufSize 10000 -numPos 170 -numNeg 330 -numStages 15 -maxFalseAlarmRate 0.2 -minHitRate 0.999999 > old_cascades/cascade_019/command.txt

rm old_cascades/cascade_019/*.xml && C:/Users/Jayare/Downloads/opencv/build/x64/vc15/bin/opencv_traincascade.exe -data old_cascades/cascade_019/ -vec pos.vec -bg neg.txt -w 24 -h 24 -precalcValBufSize 10000 -precalcIdxBufSize 10000 -numPos 170 -numNeg 330 -numStages 15 -maxFalseAlarmRate 0.25 -minHitRate 0.999999 > old_cascades/cascade_019/command.txt
git add -A
git commit -m "tweaking"
git push